---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "ghcr.io/haveagitgat/tdarr:2.17.01"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "app-config"
          ports:
            - name: http
              containerPort: 8265
              protocol: TCP
            - name: server
              containerPort: 8266
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/server
            - name: config-data
              mountPath: /app/configs
            - name: cache
              mountPath: /temp
            - name: media
              mountPath: /media
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config-data
          persistentVolumeClaim:
            claimName: config-data-pvc
        - name: cache
          hostPath:
            path: /mnt/tdarr_cache
            type: Directory
        - name: media
          hostPath:
            path: /mnt/media
            type: Directory
